# Generated by Django 3.1.6 on 2021-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supported_chains',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
