# Generated by Django 3.1.6 on 2021-02-08 17:13

from django.db import migrations


def create_blockset_service(apps, schema_editor):
    Service = apps.get_model('app', 'Service')
    Service.objects.create(name='Blockset', slug='blockset', supported_chains=[])


def create_service_update_schedule(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='1', hour='*', day_of_week='*', day_of_month='*', month_of_year='*'
    )

    PeriodicTask.objects.create(
        crontab=schedule,
        name='Update Supported Blockchains',
        task='app.tasks.update_all_supported_blockchains'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_supported_chains'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices')
    ]

    operations = [
        migrations.RunPython(create_blockset_service),
        migrations.RunPython(create_service_update_schedule)
    ]
