# Generated by Django 3.1.6 on 2021-02-08 23:15

from django.db import migrations


def create_update_all_blockchain_heights_task(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=10, period='seconds'
    )

    PeriodicTask.objects.create(
        interval=schedule,
        name='Updated block all chain heights',
        task='app.tasks.update_all_blockchain_heights'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210208_0913'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices')
    ]

    operations = [
        migrations.RunPython(create_update_all_blockchain_heights_task)
    ]
