# Generated by Django 3.1.6 on 2021-02-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210208_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=60)),
                ('is_testnet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChainHeightResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('er', 'Error'), ('wr', 'Warn')], max_length=2)),
                ('height', models.IntegerField(default=0)),
                ('error', models.TextField(default='')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blockchain')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='supported_chains',
        ),
        migrations.DeleteModel(
            name='CheckResult',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
        migrations.AddIndex(
            model_name='blockchain',
            index=models.Index(fields=['service', 'slug'], name='service_blockchain_slug'),
        ),
    ]
