# Generated by Django 3.1.6 on 2021-02-09 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210208_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bh', 'Block Height')], db_column='check_type', max_length=2)),
                ('started', models.DateTimeField()),
                ('completed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chainheightresult',
            name='duration',
            field=models.IntegerField(help_text='Duration in nanoseconds'),
        ),
        migrations.AddIndex(
            model_name='checkinstance',
            index=models.Index(fields=['type', 'completed'], name='check_type_completed'),
        ),
        migrations.AddField(
            model_name='chainheightresult',
            name='check_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.checkinstance'),
            preserve_default=False,
        ),
    ]
