# Generated by Django 3.1.6 on 2021-02-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210209_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainheightresult',
            name='difference_from_best',
            field=models.IntegerField(default=0, help_text='Difference (+/-) from best chain height'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chainheightresult',
            name='duration',
            field=models.IntegerField(help_text='Duration in milliseconds'),
        ),
    ]
