# Generated by Django 3.1.6 on 2021-02-10 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210210_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainheightresult',
            name='difference_from_best',
        ),
        migrations.AddField(
            model_name='chainheightresult',
            name='best_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.chainheightresult'),
        ),
    ]
