# Generated by Django 3.1.6 on 2021-02-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210210_0349'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkinstance',
            name='check_type_completed',
        ),
        migrations.AddIndex(
            model_name='checkinstance',
            index=models.Index(fields=['type', '-completed'], name='check_type_completed'),
        ),
    ]
