# Generated by Django 3.1.6 on 2021-02-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210211_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainmeta',
            name='height_tolerance_error',
            field=models.IntegerField(default=-2, help_text='Number of blocks behind that should sound the alarms'),
        ),
        migrations.AlterField(
            model_name='blockchainmeta',
            name='height_tolerance_warning',
            field=models.IntegerField(default=-1, help_text='Number of blocks behind that should emit a warning'),
        ),
        migrations.CreateModel(
            name='CheckError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=4)),
                ('url', models.CharField(max_length=2048)),
                ('request_headers', models.JSONField()),
                ('request_body', models.TextField(default='')),
                ('status_code', models.IntegerField()),
                ('response_headers', models.JSONField()),
                ('response_body', models.TextField(default='')),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(default='')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blockchain')),
                ('check_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.checkinstance')),
            ],
        ),
        migrations.AddField(
            model_name='chainheightresult',
            name='error_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.checkerror'),
        ),
    ]
