# Generated by Django 3.1.6 on 2021-02-11 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210211_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkerror',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='method',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='request_headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='response_headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='status_code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='url',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
