# Generated by Django 3.1.6 on 2021-02-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210211_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkerror',
            name='tag',
            field=models.CharField(choices=[('timeout', 'Timeout'), ('ssl', 'SSL Error'), ('encoding', 'Encoding Error'), ('http', 'HTTP Error'), ('system', 'System Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=10),
        ),
    ]
