# Generated by Django 3.1.6 on 2021-02-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_checkerror_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='tag',
            field=models.CharField(choices=[('timeout', 'Timeout'), ('connection', 'Connection Error'), ('ssl', 'SSL Error'), ('encoding', 'Encoding Error'), ('http', 'HTTP Error'), ('system', 'System Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=10),
        ),
    ]
