# Generated by Django 3.1.6 on 2021-02-17 03:12

from django.db import migrations, models


def create_services(apps, schema_editor):
    Service = apps.get_model('app', 'Service')
    Service.objects.create(name='Blockset DO LB', slug='blockset_do', private=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210212_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_services)
    ]
