# Generated by Django 3.1.6 on 2021-02-17 16:55

from django.db import migrations, models
import django.db.models.deletion


def create_update_all_pings_task(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=5, period='seconds'
    )

    PeriodicTask.objects.create(
        interval=schedule,
        name='Update all service pings',
        task='app.tasks.update_all_pings'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_service_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkerror',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
        migrations.AlterField(
            model_name='checkerror',
            name='blockchain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.blockchain'),
        ),
        migrations.AlterField(
            model_name='checkinstance',
            name='type',
            field=models.CharField(choices=[('bh', 'Block Height'), ('p', 'Ping')], db_column='check_type', max_length=2),
        ),
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('er', 'Error'), ('wr', 'Warn')], max_length=2)),
                ('check_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='app.checkinstance')),
                ('error_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.checkerror')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.RunPython(create_update_all_pings_task)
    ]
