# Generated by Django 3.1.6 on 2021-06-24 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210624_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvalidationresult',
            name='missing_transaction_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), default=list, help_text='Transaction IDs missing when compared to a canonical block check result', size=None),
        ),
        migrations.AlterUniqueTogether(
            name='blockvalidationresult',
            unique_together={('validation_instance', 'height')},
        ),
        migrations.RemoveField(
            model_name='blockvalidationresult',
            name='error',
        ),
        migrations.RemoveField(
            model_name='blockvalidationresult',
            name='error_details',
        ),
    ]
