# Generated by Django 3.1.6 on 2021-06-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210624_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvalidationresult',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='app.blockchain'),
        ),
        migrations.AlterField(
            model_name='blockvalidationresult',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='app.service'),
        ),
        migrations.AddIndex(
            model_name='blockvalidationresult',
            index=models.Index(fields=['height'], name='height_index'),
        ),
    ]
