# Generated by Django 3.1.6 on 2021-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210628_1528'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blockvalidationinstance',
            index=models.Index(fields=['-end_height'], name='blockvalidationresult_end'),
        ),
        migrations.AddIndex(
            model_name='chainheightresult',
            index=models.Index(fields=['-started'], name='chainheightresult_started'),
        ),
        migrations.AddIndex(
            model_name='pingresult',
            index=models.Index(fields=['-started'], name='pingresult_started'),
        ),
    ]
